# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('table_name', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('source_name', models.CharField(blank=True, max_length=256, null=True)),
                ('source_link', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'metadata',
            },
        ),
        migrations.CreateModel(
            name='NassAnimalsInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('animals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nass_animals_inventory',
            },
        ),
        migrations.CreateModel(
            name='NassAnimalsSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('animals', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nass_animals_sales',
            },
        ),
        migrations.CreateModel(
            name='NassCommodityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nass_commodity_area',
            },
        ),
        migrations.CreateModel(
            name='NassCommodityFarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('farms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nass_commodity_farms',
            },
        ),
        migrations.CreateModel(
            name='OainHarvestAcres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('harvested_acres', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'oain_harvest_acres',
            },
        ),
        migrations.CreateModel(
            name='RegionLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('co_code', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('region', models.CharField(blank=True, max_length=90, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'region_lookup',
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'spatial_ref_sys',
            },
        ),
        migrations.CreateModel(
            name='SubsidyDollars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('subsidy_dollars', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'subsidy_dollars',
            },
        ),
        migrations.CreateModel(
            name='SubsidyRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('subsidy_recipients', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'subsidy_recipients',
            },
        ),
        migrations.CreateModel(
            name='MetadataTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('table_name', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('source_name', models.CharField(blank=True, max_length=256, null=True)),
                ('source_link', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'metadata_test',
            },
        ),
        migrations.CreateModel(
            name='RegionLookupTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_code', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('co_code', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('region', models.CharField(blank=True, max_length=90, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_lookup_test',
            },
        ),
        migrations.CreateModel(
            name='SubsidyDollarsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('subsidy_dollars', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsidy_dollars_test',
            },
        ),
    ]
