# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160615_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportsHistoricalCleaned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=120, null=True)),
                ('value_num', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('hs_cat_lvl_1', models.CharField(blank=True, max_length=120, null=True)),
                ('hs_cat_lvl_2', models.CharField(blank=True, max_length=120, null=True)),
                ('time_month', models.IntegerField(blank=True, null=True)),
                ('time_year', models.IntegerField(blank=True, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'exports_historical_cleaned',
            },
        ),
    ]
