# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exportshistoricalcleaned'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawOainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(blank=True, max_length=128, null=True)),
                ('county', models.CharField(blank=True, max_length=64, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('harvest_units', models.IntegerField(blank=True, null=True)),
                ('yield_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('production_unit', models.IntegerField(blank=True, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('value_produced', models.CharField(blank=True, max_length=64, null=True)),
                ('percent_sold', models.IntegerField(blank=True, null=True)),
                ('value_sales', models.CharField(blank=True, max_length=64, null=True)),
                ('harvest_unit_of_measure', models.CharField(blank=True, max_length=32, null=True)),
                ('yield_unit_of_measure', models.CharField(blank=True, max_length=32, null=True)),
                ('production_unit_of_measure', models.CharField(blank=True, max_length=32, null=True)),
                ('price_unit_of_measure', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'raw_oain_data',
            },
        ),
    ]
